/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** Generated by script/generateAstKindConst.js — do not edit by hand. */

#pragma once

#include <cstdint>
#include <llvm/ADT/StringRef.h>

namespace ast_dumper {

constexpr uint16_t kAstKindUnknown = 0;
constexpr uint8_t kAttrUnknown = 0;

/// Pack wire node_flags from Clang JSON bool attrs (see CxxNodeFlag in ArkCxxAstNode.ts).
uint8_t PackCxxNodeFlags(bool hasInClassInitializer, bool isImplicit, bool isPostfix, bool isArrow, bool isArray);

/// Pack wire ClassBaseWire.base_flags from Clang JSON bool attrs.
uint8_t PackCxxBaseFlags(bool isVirtual);

/// Maps Clang JSON modifier keyword to wire modifier_flags bit (ModifierType layout in ArkBaseModel.ts).
uint32_t LookupModifierFlagBit(llvm::StringRef name);

/// Maps Clang JSON "kind" / "castKind" string to wire uint16 (ids match astKind in ArkCxxAstNode.ts).
uint16_t LookupAstKindId(llvm::StringRef kindName);

/// Maps Clang JSON attr strings to wire uint8 (ids match cxx* enums in ArkCxxAstNode.ts).
uint8_t LookupTagUsedId(llvm::StringRef name);
uint8_t LookupStorageClassId(llvm::StringRef name);
uint8_t LookupAccessId(llvm::StringRef name);
uint8_t LookupValueCategoryId(llvm::StringRef name);
uint8_t LookupFoldOpId(llvm::StringRef name);
uint8_t LookupOpcodeId(llvm::StringRef name);

} // namespace ast_dumper
